name: brain_blox
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_auth: ^4.17.8
  firebase_database: ^10.4.9
  firebase_storage: ^11.6.9
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  flutter_staggered_animations: ^1.1.1
  table_calendar: ^3.1.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  dio: ^5.7.0
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  flutter_pdfview: ^1.3.3
  visibility_detector: ^0.4.0+2
  animated_bottom_navigation_bar: ^1.3.3
  animations: ^2.0.11
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
